/** Section headings and fixed sentences for generated business documents. */
export interface BusinessDocCopy {
  draftNotice: string;
  placeholder: (what: string) => string;
  titles: Record<"proposal" | "agreement" | "handover" | "maintenance_agreement", string>;
  h: Record<string, string>;
  none: string;
  unset: string;
  preparedFor: (client: string) => string;
  preparedBy: (org: string) => string;
  date: (d: string) => string;
  validity: string;
  revisions: string;
  changeRequests: string;
  clientDuties: string[];
  providerDuties: string[];
  ip: string;
  confidentiality: string;
  cancellation: string;
  handoverChecklist: string[];
  warranty: (until: string | null) => string;
  maintenanceIntro: string;
  response: (hours: number | null) => string;
  fee: (amount: string, cycle: string) => string;
  cycles: Record<string, string>;
  term: (label: string, amount: string, due: string | null) => string;
  signatures: string;
}

const PH = (what: string) => `[${what}]`;

export const businessDocEn: BusinessDocCopy = {
  draftNotice:
    "> Draft generated by Saqina Dev from the project records. It is not legal advice. Review it, fill in the bracketed fields and have it checked before anyone signs it.",
  placeholder: PH,
  titles: {
    proposal: "Project Proposal",
    agreement: "Service Agreement (Draft)",
    handover: "Handover Document",
    maintenance_agreement: "Maintenance Agreement (Draft)",
  },
  h: {
    overview: "Project overview",
    objectives: "Objectives",
    scope: "Scope of work",
    included: "Included",
    excluded: "Not included",
    optional: "Optional (separate agreement)",
    future: "Future phases",
    timeline: "Timeline and milestones",
    pricing: "Project value",
    schedule: "Payment schedule",
    assumptions: "Assumptions",
    validity: "Validity",
    parties: "Parties",
    terms: "Payment terms",
    revisions: "Revisions",
    changes: "Change requests",
    clientDuties: "Client responsibilities",
    providerDuties: "Provider responsibilities",
    warranty: "Warranty",
    maintenance: "Maintenance",
    ip: "Intellectual property",
    confidentiality: "Confidentiality",
    cancellation: "Cancellation",
    handover: "Handover",
    delivered: "Delivered features",
    checklist: "Handover checklist",
    period: "Period",
    fee: "Fee",
    response: "Response time",
    signatures: "Signatures",
  },
  none: "None recorded yet.",
  unset: "To be agreed",
  preparedFor: (c) => `Prepared for: ${c}`,
  preparedBy: (o) => `Prepared by: ${o}`,
  date: (d) => `Date: ${d}`,
  validity: "This proposal is valid for 30 days from the date above.",
  revisions: `The client may request ${PH("NUMBER")} rounds of revisions per milestone within the agreed scope.`,
  changeRequests:
    "Work outside the scope above is handled as a change request with its own cost and timeline, and starts only after the client approves it in writing or on the client portal.",
  clientDuties: [
    "Provide content, accounts and feedback on time.",
    "Review and approve milestones through the client portal.",
    "Pay invoices by their due dates.",
  ],
  providerDuties: [
    "Deliver the included scope with reasonable skill and care.",
    "Keep the client informed through the client portal.",
    "Protect the client's data and credentials.",
  ],
  ip: `On full payment, rights to the delivered work transfer to the client, except third-party components under their own licences. ${PH("ADJUST IF NEEDED")}`,
  confidentiality: "Both parties keep the other's non-public information confidential.",
  cancellation: `Either party may end the agreement with ${PH("NOTICE PERIOD")} written notice. Work completed up to that date is paid.`,
  handoverChecklist: [
    "Source code and repository access transferred",
    "Admin accounts and credentials handed over securely",
    "Documentation delivered",
    "Deployment and hosting details confirmed",
    "Client confirms acceptance",
  ],
  warranty: (u) =>
    u
      ? `Defects in the delivered scope reported until ${u} are fixed at no cost. Changes and new features are not warranty work.`
      : `Warranty period: ${PH("WARRANTY PERIOD")}. Defects in the delivered scope reported in that period are fixed at no cost.`,
  maintenanceIntro:
    "Ongoing support after delivery. Warranty fixes are separate and not billed as maintenance.",
  response: (h) => (h ? `First response within ${h} hours on working days.` : PH("RESPONSE TIME")),
  fee: (a, c) => `${a} ${c}`,
  cycles: {
    monthly: "per month",
    quarterly: "per quarter",
    yearly: "per year",
    one_time: "one time",
  },
  term: (l, a, d) => `${l}: ${a}${d ? `, due ${d}` : ""}`,
  signatures: `Client: ${PH("NAME, TITLE")} ____________________\n\nProvider: ${PH("NAME, TITLE")} ____________________`,
};

export const businessDocId: BusinessDocCopy = {
  draftNotice:
    "> Draft ini disusun Saqina Dev dari catatan project. Ini bukan nasihat hukum. Periksa, lengkapi bagian dalam kurung siku, dan minta ditinjau sebelum ditandatangani.",
  placeholder: PH,
  titles: {
    proposal: "Proposal Project",
    agreement: "Perjanjian Kerja (Draft)",
    handover: "Dokumen Serah Terima",
    maintenance_agreement: "Perjanjian Maintenance (Draft)",
  },
  h: {
    overview: "Gambaran project",
    objectives: "Tujuan",
    scope: "Ruang lingkup pekerjaan",
    included: "Termasuk",
    excluded: "Tidak termasuk",
    optional: "Opsional (kesepakatan terpisah)",
    future: "Fase berikutnya",
    timeline: "Jadwal dan milestone",
    pricing: "Nilai project",
    schedule: "Jadwal pembayaran",
    assumptions: "Asumsi",
    validity: "Masa berlaku",
    parties: "Para pihak",
    terms: "Ketentuan pembayaran",
    revisions: "Revisi",
    changes: "Permintaan perubahan",
    clientDuties: "Tanggung jawab client",
    providerDuties: "Tanggung jawab penyedia",
    warranty: "Garansi",
    maintenance: "Maintenance",
    ip: "Hak kekayaan intelektual",
    confidentiality: "Kerahasiaan",
    cancellation: "Pembatalan",
    handover: "Serah terima",
    delivered: "Fitur yang diserahkan",
    checklist: "Daftar periksa serah terima",
    period: "Periode",
    fee: "Biaya",
    response: "Waktu respons",
    signatures: "Tanda tangan",
  },
  none: "Belum ada yang tercatat.",
  unset: "Akan disepakati",
  preparedFor: (c) => `Untuk: ${c}`,
  preparedBy: (o) => `Disusun oleh: ${o}`,
  date: (d) => `Tanggal: ${d}`,
  validity: "Proposal ini berlaku 30 hari sejak tanggal di atas.",
  revisions: `Client dapat meminta ${PH("JUMLAH")} putaran revisi per milestone dalam scope yang disepakati.`,
  changeRequests:
    "Pekerjaan di luar scope di atas ditangani sebagai change request dengan biaya dan waktu tersendiri, dan baru dikerjakan setelah client menyetujuinya secara tertulis atau di portal client.",
  clientDuties: [
    "Menyediakan konten, akun, dan masukan tepat waktu.",
    "Meninjau dan menyetujui milestone melalui portal client.",
    "Membayar invoice sesuai jatuh tempo.",
  ],
  providerDuties: [
    "Mengerjakan scope yang termasuk dengan cermat dan profesional.",
    "Memberi kabar perkembangan melalui portal client.",
    "Menjaga data dan kredensial milik client.",
  ],
  ip: `Setelah pelunasan, hak atas hasil pekerjaan beralih ke client, kecuali komponen pihak ketiga dengan lisensinya sendiri. ${PH("SESUAIKAN BILA PERLU")}`,
  confidentiality: "Kedua pihak menjaga kerahasiaan informasi non-publik milik pihak lain.",
  cancellation: `Masing-masing pihak dapat mengakhiri perjanjian dengan pemberitahuan tertulis ${PH("JANGKA WAKTU")}. Pekerjaan yang sudah selesai sampai tanggal itu tetap dibayar.`,
  handoverChecklist: [
    "Kode sumber dan akses repository diserahkan",
    "Akun admin dan kredensial diserahkan dengan aman",
    "Dokumentasi diserahkan",
    "Detail deployment dan hosting dikonfirmasi",
    "Client menyatakan menerima",
  ],
  warranty: (u) =>
    u
      ? `Cacat pada scope yang diserahkan dan dilaporkan sampai ${u} diperbaiki tanpa biaya. Perubahan dan fitur baru bukan pekerjaan garansi.`
      : `Masa garansi: ${PH("MASA GARANSI")}. Cacat pada scope yang diserahkan dan dilaporkan dalam masa itu diperbaiki tanpa biaya.`,
  maintenanceIntro:
    "Dukungan berkelanjutan setelah serah terima. Perbaikan garansi terpisah dan tidak ditagih sebagai maintenance.",
  response: (h) => (h ? `Respons pertama dalam ${h} jam pada hari kerja.` : PH("WAKTU RESPONS")),
  fee: (a, c) => `${a} ${c}`,
  cycles: {
    monthly: "per bulan",
    quarterly: "per kuartal",
    yearly: "per tahun",
    one_time: "sekali",
  },
  term: (l, a, d) => `${l}: ${a}${d ? `, jatuh tempo ${d}` : ""}`,
  signatures: `Client: ${PH("NAMA, JABATAN")} ____________________\n\nPenyedia: ${PH("NAMA, JABATAN")} ____________________`,
};
