/**
 * DEV ONLY. A tiny OpenAI-compatible server so the provider/model/agent pipeline can be
 * exercised end to end without a real API key. It is deterministic and labels itself as a
 * mock in every reply. Never point production at it.
 *
 *   pnpm tsx scripts/dev-ai-server.ts          → http://localhost:4100/v1
 *   key: DEV_AI_SERVER_KEY (default "dev-mock-key-0000")
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";

const MODEL = "saqina-dev-mock";

type Message = { role: string; content: string };
type Body = {
  model: string;
  messages: Message[];
  stream?: boolean;
  tools?: { function: { name: string } }[];
  tool_choice?: { function?: { name: string } };
};

const readBody = (req: IncomingMessage) =>
  new Promise<string>((resolve) => {
    let data = "";
    req.on("data", (c) => (data += c));
    req.on("end", () => resolve(data));
  });

const between = (text: string, label: string) =>
  text.match(new RegExp(`<[a-z_]+ label="${label}">\\n([\\s\\S]*?)\\n</[a-z_]+>`))?.[1] ?? "";

/** Structured answers per function name, derived only from the request text. */
function structured(name: string, prompt: string): Record<string, unknown> {
  if (name === "classify_intent") return { intent: "HELP", confidence: 0, entities: {} };
  if (name === "agent_plan") {
    const task = between(prompt, "task").split("\n")[0] || "task";
    const slug =
      task
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")
        .slice(0, 40) || "task";
    // Reads come back as tool_output blocks (the application draft block does not count).
    const hasReads = /<tool_output label="(?!application draft)/.test(prompt);
    if (!hasReads)
      return {
        summary: `Dev mock: planning "${task}". Reading the repository first.`,
        readRequests: [{ tool: "list_files", input: {} }],
      };
    return {
      summary: `Dev mock plan for "${task}": add a design note and follow-up tasks. Generated by the dev mock model, not a real model.`,
      subtasks: [`${task}: write tests`, `${task}: review the change`],
      issues: [],
      recommendations: [
        "Replace the dev mock provider with a real model before relying on these plans.",
      ],
      fileChanges: [
        {
          path: `docs/saqina/${slug}.md`,
          content: `# ${task}\n\nPlanned by the Saqina dev mock model.\n\n- [ ] Implement\n- [ ] Test\n`,
        },
      ],
      commitMessage: `docs: plan for ${task}`,
    };
  }
  return {};
}

function reply(prompt: string) {
  const draft = between(prompt, "application draft");
  return `[dev mock model] ${draft || "No draft provided."}`;
}

async function handle(req: IncomingMessage, res: ServerResponse, key: string) {
  const json = (status: number, body: unknown) => {
    res.writeHead(status, { "content-type": "application/json" });
    res.end(JSON.stringify(body));
  };
  if (req.headers.authorization !== `Bearer ${key}`)
    return json(401, { error: { message: "unauthorized" } });
  if (req.method === "GET" && req.url === "/v1/models")
    return json(200, { data: [{ id: MODEL, object: "model" }] });
  if (req.method !== "POST" || req.url !== "/v1/chat/completions")
    return json(404, { error: { message: "not found" } });

  const body = JSON.parse(await readBody(req)) as Body;
  const prompt = body.messages.map((m) => m.content).join("\n\n");
  const usage = { prompt_tokens: Math.ceil(prompt.length / 4), completion_tokens: 40 };
  const fn = body.tool_choice?.function?.name;
  if (fn) {
    return json(200, {
      choices: [
        {
          message: {
            tool_calls: [
              {
                type: "function",
                function: { name: fn, arguments: JSON.stringify(structured(fn, prompt)) },
              },
            ],
          },
        },
      ],
      usage,
    });
  }
  const text = reply(prompt);
  if (!body.stream)
    return json(200, { choices: [{ message: { role: "assistant", content: text } }], usage });
  res.writeHead(200, { "content-type": "text/event-stream" });
  for (const part of text.match(/[\s\S]{1,24}/g) ?? [text])
    res.write(`data: ${JSON.stringify({ choices: [{ delta: { content: part } }] })}\n\n`);
  res.write(`data: ${JSON.stringify({ choices: [], usage })}\n\n`);
  res.end("data: [DONE]\n\n");
}

export function startDevAiServer(
  port = 4100,
  key = process.env.DEV_AI_SERVER_KEY ?? "dev-mock-key-0000",
): Promise<Server> {
  const server = createServer((req, res) => {
    handle(req, res, key).catch(() => {
      res.writeHead(500);
      res.end();
    });
  });
  return new Promise((resolve) => server.listen(port, "127.0.0.1", () => resolve(server)));
}

if (process.argv[1]?.endsWith("dev-ai-server.ts")) {
  void startDevAiServer().then(() =>
    console.info("Dev mock AI server on http://localhost:4100/v1 (DEV ONLY)"),
  );
}
