import type { SiteContent } from "./types";

export const en: SiteContent = {
  meta: {
    title: "Saqina Dev: plan, build or hand off software without losing the thread",
    description:
      "Turn a brief into a PRD, a plan and a working project. Build it inside Saqina Dev or with your own coding agent, while the context, decisions and progress stay in one place.",
    tagline: "Build here. Build with your agent. Stay in control.",
    ogSubtitle: "Generate it here. Or bring your own agent.",
    ogFooter: "PRD · Plan · Project memory · Deploy",
  },
  hero: {
    title: "Build software your way.",
    lead: ["Generate it here.", "Or bring your own agent."],
    body: "Saqina Dev keeps your project, context, plan and progress connected.",
    primaryCta: "Start a Project",
    secondaryCta: "Explore the Workflow",
  },
  heroPaths: {
    tablist: "Ways to build",
    pathA: "path a",
    pathB: "path b",
    here: { label: "Build here", flow: ["Prompt", "Generate", "Preview", "Iterate", "Deploy"] },
    agent: {
      label: "Your own agent",
      flow: ["PRD", "Agent prompt", "Claude / Codex / Cursor / Kiro", "MCP", "Progress sync"],
    },
    shared: "Shared project context",
  },
  story: {
    title: "Watch an idea become a structured software project.",
    note: "The interview works today. Later stages are shown the way they are being built.",
    railLabel: "Story progress",
    chapters: {
      idea: {
        title: "It starts with “I have an idea.”",
        body: "One sentence is enough. Inside it are an audience, a few features, a goal and some limits, even if nobody has written them down yet.",
      },
      project: {
        title: "Let's turn it into a project.",
        body: "The interview pulls those pieces apart and lines them up: who it is for, what it must do, what success means. Everything after this builds on that structure.",
      },
      paths: {
        title: "There is more than one way to build software.",
        body: "Generate, preview and deploy inside Saqina Dev. Or take the same project to the coding agent you already trust. Both paths read and write one shared context.",
      },
      agents: {
        title: "The agent can change. The project context should not.",
        body: "Pick any agent below. Only the identity changes: the PRD, plan, tasks, memory and MCP connection stay exactly where they are.",
      },
      documents: {
        title: "Your project remembers what you decided.",
        body: "Requirements, plans, tasks and decisions live as Markdown files the project owns. Agents read them before they write a line of code.",
      },
      memory: {
        title: "Sessions end. Decisions stay.",
        body: "When a session closes, what it decided is written to MEMORY.md. The next session, yours, a teammate's or another agent's, starts from there instead of from zero.",
      },
      mcp: {
        title: "Your agent should be able to talk to the project.",
        body: "Over MCP, an external agent reads its tasks, reports progress and asks before risky changes. The same protocol layer is designed to work with agent-to-agent setups.",
      },
      approval: {
        title: "AI can move fast. You still stay in control.",
        body: "Changes that matter stop for a human decision. Try it: review the proposal and decide.",
      },
      deploy: {
        title: "From plan to code to a live URL.",
        body: "Every change goes through Git and CI. Previews come first, production after approval, on a saqina.dev subdomain or your own domain.",
      },
    },
    nodes: {
      Idea: "Idea",
      Project: "Project",
      Context: "Context",
      PRD: "PRD",
      Memory: "Memory",
      Task: "Task",
      Deploy: "Deploy",
    },
    rail: {
      Idea: "Idea",
      Project: "Project",
      "Saqina / Agent": "Saqina / Agent",
      PRD: "PRD",
      Plan: "Plan",
      Tasks: "Tasks",
      Git: "Git",
      "CI/CD": "CI/CD",
      Deploy: "Deploy",
    },
  },
  stage: {
    planned: "Planned",
    demo: "Demo",
    idea: {
      file: "idea.txt",
      sentence: [
        { text: "“I want an app for my " },
        { text: "restaurant", mark: true },
        { text: " so " },
        { text: "orders and stock", mark: true },
        { text: " stop living on " },
        { text: "paper", mark: true },
        { text: ".”" },
      ],
      fragments: [
        { kind: "audience", value: "Owner, cashier" },
        { kind: "features", value: "Orders, stock" },
        { kind: "goal", value: "No more paper" },
        { kind: "constraint", value: "Small budget" },
      ],
    },
    project: {
      file: "project / restaurant-pos",
      structured: "structured",
      name: "Restaurant POS",
      rows: [
        { key: "Audience", value: "Owner · Manager · Cashier" },
        { key: "Core", value: "Sales · Inventory · Reports" },
        { key: "Goal", value: "Replace paper orders and stock books" },
        { key: "Constraints", value: "Small budget · works on a tablet" },
      ],
      complexity: "Complexity",
      complexityValue: "medium",
      ready: "Ready for a plan",
    },
    paths: {
      project: "Project",
      pathA: "path a",
      pathB: "path b",
      here: "Build in Saqina Dev",
      agent: "Use your own agent",
      hereItems: ["Generate", "Preview", "Iterate", "Git", "CI/CD", "Deploy"],
      shared: "Shared project context",
    },
    agents: {
      file: "project / restaurant-pos / agent",
      legend: "Choose an agent",
      generic: "Generic",
      yourAgent: "Your agent",
      unchanged: "unchanged",
      context: ["PRD.md", "PLAN.md", "TASKS.md", "MEMORY.md", "MCP connection"],
      switches: "agent switches",
      contextChanges: "context changes",
    },
    documents: {
      file: "project / school-management / docs",
      tablist: "Project documents",
      docs: [
        {
          name: "PRD.md",
          lines: [
            "# School Management Platform",
            "## Objective",
            "Parents see attendance and grades without calling the school.",
            "## Users",
            "Admin · Teacher · Student · Parent",
            "## Requirements",
            "- Teachers record attendance in under a minute",
            "- Parents get a weekly summary",
          ],
        },
        {
          name: "PLAN.md",
          lines: [
            "# Plan",
            "## Milestone 1: Attendance",
            "- Class roster import",
            "- Daily attendance screen",
            "## Milestone 2: Grades",
            "- Grade book per subject",
          ],
        },
        {
          name: "TASKS.md",
          lines: [
            "- [x] Roster schema",
            "- [x] Import from spreadsheet",
            "- [ ] Attendance screen (in progress)",
            "- [ ] Parent weekly summary",
          ],
        },
        {
          name: "MEMORY.md",
          lines: [
            "- Parents log in with a magic link, no passwords.",
            "- Grades are hidden until the teacher publishes them.",
            "- Rejected: SMS notifications (cost).",
          ],
        },
        {
          name: "DECISIONS.md",
          lines: [
            "## ADR-002: Supabase for auth and data",
            "Reason: row level security per school.",
          ],
        },
        {
          name: "CHANGELOG.md",
          lines: ["## v0.2.0", "Added: roster import", "Fixed: duplicate students on re-import"],
        },
      ],
    },
    memory: {
      file: "sessions",
      session1: "session 01 · cursor",
      decision: "Decision: parents log in with a magic link, no passwords.",
      memoryLine: "+ Parents log in with a magic link, no passwords.",
      sessionEnds: "session ends",
      session2: "session 02 · claude",
      restored: "Memory restored: 4 decisions. Building the parent login with a magic link.",
    },
    mcp: {
      file: "mcp / school-management",
      task: "Attendance screen",
      history: "Task status history",
      log: [
        "task.update  attendance-screen  in_progress",
        "change.propose  add attendance.status column",
        "approval.granted  by you",
        "task.complete  attendance-screen",
      ],
    },
    approval: {
      file: "ai proposal · agent: codex",
      title: "Update authentication architecture",
      impact: "Impact: 6 files · 1 migration",
      review: "Review proposal",
      required: "Approval required",
      reject: "Reject",
      revision: "Request Revision",
      approve: "Approve",
      changes: [
        "Move sessions from localStorage JWT to httpOnly cookies",
        "Add CSRF token to form posts",
        "Migration: sessions table with expiry",
      ],
      outcomes: {
        approved: "Approved. The task continues: the agent applies the change and opens a preview.",
        revision: "Sent back. The agent revises the proposal and asks again.",
        rejected: "Rejected. The change is dropped and recorded in DECISIONS.md.",
      },
      continues: ["Approved", "Applying change", "Preview build", "Task continues"],
      again: "Run the demo again",
    },
    deploy: {
      file: "pipeline / restaurant-pos",
      stages: ["Git", "Build", "Test", "Preview", "Deploy"],
      production: "Production",
    },
  },
  beforeAfter: {
    title: "From a vague idea to a project you can build.",
    before: "“I want an app for my business.”",
    beforeLabel: "before",
    afterLabel: "after",
    after: [
      { label: "Clear project", value: "Restaurant POS" },
      { label: "Clear users", value: "Owner · Manager · Cashier" },
      { label: "Clear features", value: "Sales · Inventory · Reports" },
      { label: "Clear architecture", value: "Next.js · Supabase" },
      { label: "Clear development path", value: "Build in Saqina Dev" },
      { label: "Clear deployment", value: "restaurant-pos.saqina.dev" },
    ],
  },
  infra: {
    title: "Infrastructure you already know.",
    body: "Projects deploy through Vercel and store data in Supabase, connected to your accounts or created for you. Every project gets a saqina.dev address, and your own domain when you want it.",
    mapLabel: "Saqina Dev connects to Vercel and Supabase and ships to a saqina.dev subdomain",
    vercel: { role: "Deploy", items: ["Connect existing Vercel", "Create Vercel project"] },
    supabase: { role: "Database", items: ["Connect Supabase", "Create Supabase project"] },
    domainAlt: "or your custom domain",
    terminalCaption: "Example output, planned CLI",
    terminalProject: "Project:",
    terminalVersion: "Version:",
  },
  demo: {
    title: "Describe a project. See how Saqina reads it.",
    body: "This runs a local preview engine in your browser. No AI call, nothing is saved.",
    label: "Describe your project",
    placeholder: "I want to build…",
    error: "Write a few words about what you want to build.",
    submit: "Read my idea",
    tryOne: "Or try one:",
    examples: [
      "Build a POS for a small restaurant",
      "A school management platform for parents and teachers",
      "A marketplace for local artisans",
      "An AI tool that summarizes contracts",
      "A portfolio for an architect",
    ],
    empty:
      "Your project's first reading appears here: type, likely users, stack, how to build it and a landing concept.",
    understood: "Understood",
    accepted: "Recommendation accepted",
    why: "Why this recommendation?",
    unmatched:
      "This idea did not match a known project shape, so the interview will ask a few more questions.",
    edit: "Edit",
    accept: "Accept Recommendation",
    start: "Start Project",
    starting: "Opening the interview…",
    rows: {
      type: "Project type",
      users: "Likely users",
      usersUnknown: "Asked in the interview",
      frontend: "Frontend",
      backend: "Backend",
      backendValue: "Next.js API routes",
      database: "Database",
      auth: "Authentication",
      authRoles: "Role-based",
      authEmail: "Email login",
      authNone: "Not needed",
      development: "Development",
      landing: "Landing concept",
      noLanding: "No public landing page",
    },
  },
  useCases: {
    file: "docs/use-cases.md",
    title: "Start from a brief, not a tech stack",
    intro:
      "You do not need to know which framework or database to pick. Describe the outcome; the interview works out the rest and explains why.",
    start: "Start this brief",
    items: [
      {
        type: "school-website",
        label: "School Website",
        brief: "Admissions online and one page per program.",
      },
      {
        type: "company-profile",
        label: "Company Profile",
        brief: "Show our services and get more contact requests.",
      },
      { type: "pos", label: "POS", brief: "Faster checkout and stock that updates itself." },
      { type: "marketplace", label: "Marketplace", brief: "Local sellers listing handmade goods." },
      { type: "saas", label: "SaaS", brief: "Teams track field visits and bill monthly." },
      {
        type: "internal-dashboard",
        label: "Internal System",
        brief: "Replace the spreadsheet our ops team lives in.",
      },
      {
        type: "ai-application",
        label: "AI Application",
        brief: "Upload a contract, get the risky clauses.",
      },
      {
        type: "booking",
        label: "Booking System",
        brief: "Clients book a session and get a reminder.",
      },
      {
        type: "portfolio",
        label: "Portfolio",
        brief: "Architecture work, presented project by project.",
      },
      {
        type: "custom",
        label: "Custom Web App",
        brief: "Something specific. Start with a paragraph.",
      },
    ],
  },
  finalCta: {
    node: "your-project · Idea",
    lines: ["You bring the idea.", "We help structure the project.", "You choose how to build it."],
    primary: "Start a Project",
    secondary: "Explore the Workflow",
  },
  footer: { tagline: ["Build here.", "Bring your own agent.", "Stay in control."] },
};
