import type { SiteContent } from "./types";

export const en: SiteContent = {
  meta: {
    title: "Saqina Dev: from idea and deal to build and maintenance",
    description:
      "One workspace for client projects: scope, agreements, invoices, payments, development and maintenance, with AI that knows the whole project and a portal for your client.",
    tagline: "From idea, deal and build to maintenance.",
    ogSubtitle: "Manage projects. Build with AI. Keep clients in the loop.",
    ogFooter: "Clients · Scope · Invoices · Build · Maintenance",
  },
  hero: {
    title: "From idea and deal to build and maintenance.",
    lead: "One workspace for your client projects.",
    points: [
      "Scope, agreements and invoices on the project",
      "A portal so the client sees progress",
      "AI that builds and answers from your records",
    ],
    primaryCta: "Start a Project",
    secondaryCta: "See How It Works",
    cards: [
      { label: "Client", value: "PT Rasa Nusantara" },
      { label: "Scope", value: "6 included · 3 excluded" },
      { label: "Invoice", value: "DP paid · IDR 8,000,000" },
      { label: "Build", value: "Review in progress" },
      { label: "Maintenance", value: "Monthly care" },
    ],
  },
  lifecycle: {
    file: "how it works",
    title: "Nine steps, one project.",
    steps: [
      { name: "Idea", point: "Saqina reads the client's message." },
      { name: "Client", point: "Client and project saved together." },
      { name: "Scope", point: "Included, excluded, future." },
      { name: "Agreement", point: "Proposal and agreement drafts." },
      { name: "Payment", point: "Terms, invoices, payments recorded." },
      { name: "Build", point: "Saqina or your own coding agent." },
      { name: "Review", point: "Client approves on the portal." },
      { name: "Delivery", point: "Live, with a handover document." },
      { name: "Maintenance", point: "Warranty, plans, renewal reminders." },
    ],
    pause: "Pause",
    play: "Play",
  },
  pillars: {
    file: "what you get",
    title: "Three things, connected.",
    items: [
      {
        id: "project",
        name: "One project",
        points: [
          "Client, scope and money in one place",
          "Change requests before extra work",
          "Nothing lost between deal and code",
        ],
      },
      {
        id: "portal",
        name: "Client portal",
        points: [
          "Progress in plain language",
          "Invoices, payments, documents",
          "Approvals and requests on record",
        ],
      },
      {
        id: "ai",
        name: "Ask Saqina",
        points: [
          "Answers from records, never invented",
          "Prepares changes, you approve",
          "Builds with you when it is time",
        ],
      },
    ],
    orbit: ["Client", "Scope", "Invoice", "Build", "Docs", "Care"],
    portal: { label: "Progress", value: "IDR 6,000,000", due: "Due 30 Oct" },
    prompts: [
      "Make an agreement draft.",
      "How much is still unpaid?",
      "Is online payment in scope?",
      "Remind the client about the invoice.",
    ],
  },
  demo: {
    title: "Describe a project. See how Saqina reads it.",
    body: "This runs a local preview engine in your browser. No AI call, nothing is saved.",
    label: "Describe your project",
    placeholder: "I want to build…",
    error: "Write a few words about what you want to build.",
    submit: "Read my idea",
    tryOne: "Or try one:",
    examples: [
      "Build a POS for a small restaurant",
      "A school management platform for parents and teachers",
      "A marketplace for local artisans",
      "An AI tool that summarizes contracts",
      "A portfolio for an architect",
    ],
    empty:
      "Your project's first reading appears here: type, likely users, stack, how to build it and a landing concept.",
    understood: "Understood",
    accepted: "Recommendation accepted",
    why: "Why this recommendation?",
    unmatched:
      "This idea did not match a known project shape, so the interview will ask a few more questions.",
    edit: "Edit",
    accept: "Accept Recommendation",
    start: "Start Project",
    starting: "Opening the interview…",
    rows: {
      type: "Project type",
      users: "Likely users",
      usersUnknown: "Asked in the interview",
      frontend: "Frontend",
      backend: "Backend",
      backendValue: "Next.js API routes",
      database: "Database",
      auth: "Authentication",
      authRoles: "Role-based",
      authEmail: "Email login",
      authNone: "Not needed",
      development: "Development",
      landing: "Landing concept",
      noLanding: "No public landing page",
    },
  },
  finalCta: {
    title: "Start with one project.",
    body: "Bring the next client request. Saqina keeps the rest connected.",
    primary: "Start a Project",
    secondary: "Try the preview",
  },
  footer: { tagline: ["Manage projects.", "Build with AI.", "Keep clients in the loop."] },
};
