import type { SiteContent } from "./types";

export const id: SiteContent = {
  meta: {
    title: "Saqina Dev: dari ide, deal, build, sampai maintenance",
    description:
      "Satu workspace untuk proyek client: scope, perjanjian, invoice, pembayaran, development, dan maintenance, dengan AI yang memahami seluruh proyek dan portal untuk client Anda.",
    tagline: "Dari ide, deal, build, sampai maintenance.",
    ogSubtitle: "Kelola proyek. Build dengan AI. Client selalu tahu progresnya.",
    ogFooter: "Client · Scope · Invoice · Build · Maintenance",
  },
  hero: {
    title: "Dari ide, deal, build, sampai maintenance.",
    lead: "Satu workspace untuk proyek client Anda.",
    points: [
      "Scope, perjanjian, dan invoice menempel di proyek",
      "Portal agar client melihat progres",
      "AI yang membangun dan menjawab dari catatan Anda",
    ],
    primaryCta: "Mulai Proyek",
    secondaryCta: "Lihat Cara Kerjanya",
    cards: [
      { label: "Client", value: "PT Rasa Nusantara" },
      { label: "Scope", value: "6 termasuk · 3 tidak" },
      { label: "Invoice", value: "DP lunas · Rp8.000.000" },
      { label: "Build", value: "Sedang direview" },
      { label: "Maintenance", value: "Perawatan bulanan" },
    ],
  },
  lifecycle: {
    file: "cara kerja",
    title: "Sembilan langkah, satu proyek.",
    steps: [
      { name: "Ide", point: "Saqina membaca pesan client." },
      { name: "Client", point: "Client dan proyek tersimpan bersama." },
      { name: "Scope", point: "Termasuk, tidak termasuk, nanti." },
      { name: "Perjanjian", point: "Draft proposal dan perjanjian." },
      { name: "Pembayaran", point: "Termin, invoice, pembayaran tercatat." },
      { name: "Build", point: "Saqina atau coding agent Anda." },
      { name: "Review", point: "Client menyetujui di portal." },
      { name: "Serah terima", point: "Live, dengan dokumen serah terima." },
      { name: "Maintenance", point: "Garansi, plan, pengingat perpanjangan." },
    ],
    pause: "Jeda",
    play: "Putar",
  },
  pillars: {
    file: "yang Anda dapat",
    title: "Tiga hal, saling terhubung.",
    items: [
      {
        id: "project",
        name: "Satu proyek",
        points: [
          "Client, scope, dan uang di satu tempat",
          "Change request sebelum kerja tambahan",
          "Tidak ada yang hilang antara deal dan kode",
        ],
      },
      {
        id: "portal",
        name: "Portal client",
        points: [
          "Progres dalam bahasa sehari-hari",
          "Invoice, pembayaran, dokumen",
          "Persetujuan dan permintaan tercatat",
        ],
      },
      {
        id: "ai",
        name: "Tanya Saqina",
        points: [
          "Jawaban dari catatan, tidak dikarang",
          "Menyiapkan perubahan, Anda menyetujui",
          "Ikut membangun saat waktunya",
        ],
      },
    ],
    orbit: ["Client", "Scope", "Invoice", "Build", "Dokumen", "Care"],
    portal: { label: "Progres", value: "Rp6.000.000", due: "Jatuh tempo 30 Okt" },
    prompts: [
      "Buatkan draft perjanjian.",
      "Berapa yang belum lunas?",
      "Pembayaran online termasuk scope?",
      "Ingatkan client soal invoice.",
    ],
  },
  demo: {
    title: "Jelaskan proyek. Lihat cara Saqina membacanya.",
    body: "Ini menjalankan engine pratinjau lokal di browser Anda. Tidak ada panggilan AI, tidak ada yang disimpan.",
    label: "Jelaskan proyek Anda",
    placeholder: "Saya ingin membangun…",
    error: "Tulis beberapa kata tentang apa yang ingin Anda bangun.",
    submit: "Baca ide saya",
    tryOne: "Atau coba salah satu:",
    examples: [
      "Aplikasi kasir untuk restoran kecil",
      "Sistem informasi sekolah untuk orang tua dan guru",
      "Marketplace untuk pengrajin lokal",
      "Tool AI untuk meringkas kontrak",
      "Portofolio untuk arsitek",
    ],
    empty:
      "Bacaan pertama proyek Anda muncul di sini: jenis, kemungkinan pengguna, stack, cara membangun dan konsep landing page.",
    understood: "Dipahami",
    accepted: "Rekomendasi diterima",
    why: "Mengapa rekomendasi ini?",
    unmatched:
      "Ide ini belum cocok dengan bentuk proyek yang dikenal, jadi interview akan menanyakan beberapa hal lagi.",
    edit: "Ubah",
    accept: "Terima Rekomendasi",
    start: "Mulai Proyek",
    starting: "Membuka interview…",
    rows: {
      type: "Jenis proyek",
      users: "Kemungkinan pengguna",
      usersUnknown: "Ditanyakan di interview",
      frontend: "Frontend",
      backend: "Backend",
      backendValue: "Next.js API routes",
      database: "Database",
      auth: "Autentikasi",
      authRoles: "Berbasis peran",
      authEmail: "Login email",
      authNone: "Tidak perlu",
      development: "Pengembangan",
      landing: "Konsep landing",
      noLanding: "Tidak ada landing page publik",
    },
  },
  finalCta: {
    title: "Mulai dari satu proyek.",
    body: "Bawa permintaan client berikutnya. Saqina menjaga sisanya tetap terhubung.",
    primary: "Mulai Proyek",
    secondary: "Coba pratinjaunya",
  },
  footer: { tagline: ["Kelola proyek.", "Build dengan AI.", "Client selalu tahu progresnya."] },
};
