import type { SiteContent } from "./types";

export const id: SiteContent = {
  meta: {
    title: "Saqina Dev: rencanakan, bangun atau serahkan software tanpa kehilangan konteks",
    description:
      "Ubah brief menjadi PRD, rencana dan proyek yang berjalan. Bangun di Saqina Dev atau dengan agent coding Anda sendiri, sementara konteks, keputusan dan progres tetap di satu tempat.",
    tagline: "Bangun di sini. Bangun dengan agent Anda. Tetap memegang kendali.",
    ogSubtitle: "Buat di sini. Atau bawa agent Anda sendiri.",
    ogFooter: "PRD · Rencana · Memori proyek · Deploy",
  },
  hero: {
    title: "Bangun software dengan cara Anda.",
    lead: ["Buat di sini.", "Atau bawa agent Anda sendiri."],
    body: "Saqina Dev menjaga proyek, konteks, rencana dan progres Anda tetap terhubung.",
    primaryCta: "Mulai Proyek",
    secondaryCta: "Lihat Alur Kerjanya",
  },
  heroPaths: {
    tablist: "Cara membangun",
    pathA: "jalur a",
    pathB: "jalur b",
    here: { label: "Bangun di sini", flow: ["Prompt", "Generate", "Preview", "Iterasi", "Deploy"] },
    agent: {
      label: "Agent Anda sendiri",
      flow: [
        "PRD",
        "Prompt agent",
        "Claude / Codex / Cursor / Kiro",
        "MCP",
        "Sinkronisasi progres",
      ],
    },
    shared: "Konteks proyek bersama",
  },
  story: {
    title: "Lihat sebuah ide menjadi proyek software yang terstruktur.",
    note: "Interview sudah bisa dipakai sekarang. Tahap berikutnya ditampilkan sesuai yang sedang dibangun.",
    railLabel: "Progres cerita",
    chapters: {
      idea: {
        title: "Semua berawal dari “Saya punya ide.”",
        body: "Satu kalimat sudah cukup. Di dalamnya ada pengguna, beberapa fitur, tujuan dan batasan, walaupun belum ada yang menuliskannya.",
      },
      project: {
        title: "Mari jadikan proyek.",
        body: "Interview memilah bagian-bagian itu lalu menyusunnya: untuk siapa, harus bisa apa, dan seperti apa keberhasilannya. Semua langkah berikutnya dibangun di atas struktur ini.",
      },
      paths: {
        title: "Ada lebih dari satu cara membangun software.",
        body: "Buat, preview dan deploy di dalam Saqina Dev. Atau bawa proyek yang sama ke agent coding yang sudah Anda percaya. Kedua jalur membaca dan menulis konteks bersama yang sama.",
      },
      agents: {
        title: "Agent boleh berganti. Konteks proyek tidak.",
        body: "Pilih agent mana pun di bawah. Hanya identitasnya yang berubah: PRD, rencana, tugas, memori dan koneksi MCP tetap di tempatnya.",
      },
      documents: {
        title: "Proyek Anda mengingat apa yang sudah diputuskan.",
        body: "Kebutuhan, rencana, tugas dan keputusan disimpan sebagai file Markdown milik proyek. Agent membacanya sebelum menulis satu baris kode.",
      },
      memory: {
        title: "Sesi berakhir. Keputusan tetap ada.",
        body: "Saat sesi ditutup, keputusannya ditulis ke MEMORY.md. Sesi berikutnya, oleh Anda, rekan tim atau agent lain, mulai dari sana, bukan dari nol.",
      },
      mcp: {
        title: "Agent Anda harus bisa berbicara dengan proyek.",
        body: "Lewat MCP, agent eksternal membaca tugasnya, melaporkan progres dan bertanya sebelum perubahan berisiko. Lapisan protokol yang sama dirancang untuk alur agent-to-agent.",
      },
      approval: {
        title: "AI bisa bergerak cepat. Anda tetap memegang kendali.",
        body: "Perubahan penting berhenti untuk keputusan manusia. Coba sendiri: tinjau usulannya dan putuskan.",
      },
      deploy: {
        title: "Dari rencana ke kode ke URL yang hidup.",
        body: "Setiap perubahan melewati Git dan CI. Preview lebih dulu, produksi setelah disetujui, di subdomain saqina.dev atau domain Anda sendiri.",
      },
    },
    nodes: {
      Idea: "Ide",
      Project: "Proyek",
      Context: "Konteks",
      PRD: "PRD",
      Memory: "Memori",
      Task: "Tugas",
      Deploy: "Deploy",
    },
    rail: {
      Idea: "Ide",
      Project: "Proyek",
      "Saqina / Agent": "Saqina / Agent",
      PRD: "PRD",
      Plan: "Rencana",
      Tasks: "Tugas",
      Git: "Git",
      "CI/CD": "CI/CD",
      Deploy: "Deploy",
    },
  },
  stage: {
    planned: "Direncanakan",
    demo: "Demo",
    idea: {
      file: "ide.txt",
      sentence: [
        { text: "“Saya ingin aplikasi untuk " },
        { text: "restoran", mark: true },
        { text: " saya supaya " },
        { text: "pesanan dan stok", mark: true },
        { text: " tidak lagi dicatat di " },
        { text: "kertas", mark: true },
        { text: ".”" },
      ],
      fragments: [
        { kind: "pengguna", value: "Pemilik, kasir" },
        { kind: "fitur", value: "Pesanan, stok" },
        { kind: "tujuan", value: "Tanpa kertas" },
        { kind: "batasan", value: "Anggaran kecil" },
      ],
    },
    project: {
      file: "proyek / restaurant-pos",
      structured: "terstruktur",
      name: "POS Restoran",
      rows: [
        { key: "Pengguna", value: "Pemilik · Manajer · Kasir" },
        { key: "Inti", value: "Penjualan · Inventaris · Laporan" },
        { key: "Tujuan", value: "Menggantikan buku pesanan dan stok" },
        { key: "Batasan", value: "Anggaran kecil · jalan di tablet" },
      ],
      complexity: "Kompleksitas",
      complexityValue: "sedang",
      ready: "Siap dibuatkan rencana",
    },
    paths: {
      project: "Proyek",
      pathA: "jalur a",
      pathB: "jalur b",
      here: "Bangun di Saqina Dev",
      agent: "Pakai agent sendiri",
      hereItems: ["Generate", "Preview", "Iterasi", "Git", "CI/CD", "Deploy"],
      shared: "Konteks proyek bersama",
    },
    agents: {
      file: "proyek / restaurant-pos / agent",
      legend: "Pilih agent",
      generic: "Generik",
      yourAgent: "Agent Anda",
      unchanged: "tidak berubah",
      context: ["PRD.md", "PLAN.md", "TASKS.md", "MEMORY.md", "Koneksi MCP"],
      switches: "ganti agent",
      contextChanges: "perubahan konteks",
    },
    documents: {
      file: "proyek / school-management / docs",
      tablist: "Dokumen proyek",
      docs: [
        {
          name: "PRD.md",
          lines: [
            "# Platform Manajemen Sekolah",
            "## Tujuan",
            "Orang tua melihat absensi dan nilai tanpa menelepon sekolah.",
            "## Pengguna",
            "Admin · Guru · Siswa · Orang tua",
            "## Kebutuhan",
            "- Guru mencatat absensi dalam waktu kurang dari satu menit",
            "- Orang tua mendapat ringkasan mingguan",
          ],
        },
        {
          name: "PLAN.md",
          lines: [
            "# Rencana",
            "## Milestone 1: Absensi",
            "- Impor daftar siswa per kelas",
            "- Layar absensi harian",
            "## Milestone 2: Nilai",
            "- Buku nilai per mata pelajaran",
          ],
        },
        {
          name: "TASKS.md",
          lines: [
            "- [x] Skema daftar siswa",
            "- [x] Impor dari spreadsheet",
            "- [ ] Layar absensi (sedang dikerjakan)",
            "- [ ] Ringkasan mingguan untuk orang tua",
          ],
        },
        {
          name: "MEMORY.md",
          lines: [
            "- Orang tua masuk dengan magic link, tanpa password.",
            "- Nilai disembunyikan sampai guru menerbitkannya.",
            "- Ditolak: notifikasi SMS (biaya).",
          ],
        },
        {
          name: "DECISIONS.md",
          lines: [
            "## ADR-002: Supabase untuk autentikasi dan data",
            "Alasan: row level security per sekolah.",
          ],
        },
        {
          name: "CHANGELOG.md",
          lines: [
            "## v0.2.0",
            "Ditambahkan: impor daftar siswa",
            "Diperbaiki: siswa ganda saat impor ulang",
          ],
        },
      ],
    },
    memory: {
      file: "sesi",
      session1: "sesi 01 · cursor",
      decision: "Keputusan: orang tua masuk dengan magic link, tanpa password.",
      memoryLine: "+ Orang tua masuk dengan magic link, tanpa password.",
      sessionEnds: "sesi berakhir",
      session2: "sesi 02 · claude",
      restored: "Memori dipulihkan: 4 keputusan. Membangun login orang tua dengan magic link.",
    },
    mcp: {
      file: "mcp / school-management",
      task: "Layar absensi",
      history: "Riwayat status tugas",
      log: [
        "task.update  attendance-screen  in_progress",
        "change.propose  add attendance.status column",
        "approval.granted  by you",
        "task.complete  attendance-screen",
      ],
    },
    approval: {
      file: "usulan ai · agent: codex",
      title: "Perbarui arsitektur autentikasi",
      impact: "Dampak: 6 file · 1 migrasi",
      review: "Tinjau usulan",
      required: "Butuh persetujuan",
      reject: "Tolak",
      revision: "Minta Revisi",
      approve: "Setujui",
      changes: [
        "Pindahkan sesi dari JWT di localStorage ke cookie httpOnly",
        "Tambahkan token CSRF pada form",
        "Migrasi: tabel sesi dengan masa berlaku",
      ],
      outcomes: {
        approved: "Disetujui. Tugas berlanjut: agent menerapkan perubahan dan membuka preview.",
        revision: "Dikembalikan. Agent merevisi usulan lalu bertanya lagi.",
        rejected: "Ditolak. Perubahan dibatalkan dan dicatat di DECISIONS.md.",
      },
      continues: ["Disetujui", "Menerapkan perubahan", "Build preview", "Tugas berlanjut"],
      again: "Ulangi demo",
    },
    deploy: {
      file: "pipeline / restaurant-pos",
      stages: ["Git", "Build", "Test", "Preview", "Deploy"],
      production: "Produksi",
    },
  },
  beforeAfter: {
    title: "Dari ide yang samar ke proyek yang bisa dibangun.",
    before: "“Saya ingin aplikasi untuk bisnis saya.”",
    beforeLabel: "sebelum",
    afterLabel: "sesudah",
    after: [
      { label: "Proyek jelas", value: "POS Restoran" },
      { label: "Pengguna jelas", value: "Pemilik · Manajer · Kasir" },
      { label: "Fitur jelas", value: "Penjualan · Inventaris · Laporan" },
      { label: "Arsitektur jelas", value: "Next.js · Supabase" },
      { label: "Jalur pengembangan jelas", value: "Bangun di Saqina Dev" },
      { label: "Deployment jelas", value: "restaurant-pos.saqina.dev" },
    ],
  },
  infra: {
    title: "Infrastruktur yang sudah Anda kenal.",
    body: "Proyek di-deploy lewat Vercel dan menyimpan data di Supabase, terhubung ke akun Anda atau dibuatkan untuk Anda. Setiap proyek mendapat alamat saqina.dev, dan domain sendiri kapan pun Anda mau.",
    mapLabel: "Saqina Dev terhubung ke Vercel dan Supabase lalu rilis ke subdomain saqina.dev",
    vercel: { role: "Deploy", items: ["Hubungkan Vercel yang sudah ada", "Buat proyek Vercel"] },
    supabase: { role: "Database", items: ["Hubungkan Supabase", "Buat proyek Supabase"] },
    domainAlt: "atau domain Anda sendiri",
    terminalCaption: "Contoh output, CLI yang direncanakan",
    terminalProject: "Project:",
    terminalVersion: "Version:",
  },
  demo: {
    title: "Jelaskan proyek. Lihat cara Saqina membacanya.",
    body: "Ini menjalankan engine pratinjau lokal di browser Anda. Tidak ada panggilan AI, tidak ada yang disimpan.",
    label: "Jelaskan proyek Anda",
    placeholder: "Saya ingin membangun…",
    error: "Tulis beberapa kata tentang apa yang ingin Anda bangun.",
    submit: "Baca ide saya",
    tryOne: "Atau coba salah satu:",
    examples: [
      "Aplikasi kasir untuk restoran kecil",
      "Sistem informasi sekolah untuk orang tua dan guru",
      "Marketplace untuk pengrajin lokal",
      "Tool AI untuk meringkas kontrak",
      "Portofolio untuk arsitek",
    ],
    empty:
      "Bacaan pertama proyek Anda muncul di sini: jenis, kemungkinan pengguna, stack, cara membangun dan konsep landing page.",
    understood: "Dipahami",
    accepted: "Rekomendasi diterima",
    why: "Mengapa rekomendasi ini?",
    unmatched:
      "Ide ini belum cocok dengan bentuk proyek yang dikenal, jadi interview akan menanyakan beberapa hal lagi.",
    edit: "Ubah",
    accept: "Terima Rekomendasi",
    start: "Mulai Proyek",
    starting: "Membuka interview…",
    rows: {
      type: "Jenis proyek",
      users: "Kemungkinan pengguna",
      usersUnknown: "Ditanyakan di interview",
      frontend: "Frontend",
      backend: "Backend",
      backendValue: "Next.js API routes",
      database: "Database",
      auth: "Autentikasi",
      authRoles: "Berbasis peran",
      authEmail: "Login email",
      authNone: "Tidak perlu",
      development: "Pengembangan",
      landing: "Konsep landing",
      noLanding: "Tidak ada landing page publik",
    },
  },
  useCases: {
    file: "docs/use-cases.md",
    title: "Mulai dari brief, bukan dari tech stack",
    intro:
      "Anda tidak perlu tahu framework atau database mana yang harus dipilih. Jelaskan hasil yang diinginkan; interview menyusun sisanya dan menjelaskan alasannya.",
    start: "Mulai brief ini",
    items: [
      {
        type: "school-website",
        label: "Website Sekolah",
        brief: "Pendaftaran online dan satu halaman per program.",
      },
      {
        type: "company-profile",
        label: "Company Profile",
        brief: "Tampilkan layanan kami dan dapatkan lebih banyak permintaan kontak.",
      },
      { type: "pos", label: "POS", brief: "Kasir lebih cepat dan stok yang ter-update sendiri." },
      {
        type: "marketplace",
        label: "Marketplace",
        brief: "Penjual lokal menampilkan produk buatan tangan.",
      },
      {
        type: "saas",
        label: "SaaS",
        brief: "Tim mencatat kunjungan lapangan dan membayar bulanan.",
      },
      {
        type: "internal-dashboard",
        label: "Sistem Internal",
        brief: "Gantikan spreadsheet yang dipakai tim operasional setiap hari.",
      },
      {
        type: "ai-application",
        label: "Aplikasi AI",
        brief: "Unggah kontrak, dapatkan klausul yang berisiko.",
      },
      {
        type: "booking",
        label: "Sistem Booking",
        brief: "Klien memesan sesi dan mendapat pengingat.",
      },
      {
        type: "portfolio",
        label: "Portofolio",
        brief: "Karya arsitektur, ditampilkan proyek demi proyek.",
      },
      {
        type: "custom",
        label: "Aplikasi Web Kustom",
        brief: "Sesuatu yang spesifik. Mulai dengan satu paragraf.",
      },
    ],
  },
  finalCta: {
    node: "proyek-anda · Ide",
    lines: [
      "Anda membawa idenya.",
      "Kami bantu menyusun proyeknya.",
      "Anda pilih cara membangunnya.",
    ],
    primary: "Mulai Proyek",
    secondary: "Lihat Alur Kerjanya",
  },
  footer: { tagline: ["Bangun di sini.", "Bawa agent Anda sendiri.", "Tetap memegang kendali."] },
};
