import type { GeneratorCopy } from "./types";

export const en: GeneratorCopy = {
  priorities: { critical: "Critical", high: "High", medium: "Medium", low: "Low" },
  statuses: {
    confirmed: "Confirmed",
    inferred: "Inferred",
    unknown: "Unknown",
    conflicting: "Conflicting",
  },
  inferredMark: "(inferred, confirm)",
  none: "None identified yet.",
  toBeDefined: "To be defined.",
  prd: {
    title: "Product Requirements Document",
    draftNote:
      "Draft generated from the project interview. Items marked inferred were not stated directly; confirm or edit them.",
    headings: [
      "Overview",
      "Problem",
      "Goals",
      "Non-Goals",
      "Target Users",
      "User Roles",
      "Core Features",
      "User Flows",
      "Functional Requirements",
      "Non-Functional Requirements",
      "Integrations",
      "Data Requirements",
      "Security",
      "UX Requirements",
      "Technical Recommendations",
      "Risks",
      "Open Questions",
      "Acceptance Criteria",
    ],
    type: "Type",
    complexity: "Complexity",
    problem: (objective) => `The product exists to: ${objective}`,
    noObjective:
      "The problem has not been described yet. Add it in the interview or edit this section.",
    goalFeature: (feature) => `Deliver ${feature} for the first release.`,
    nonGoalsIntro: "Not part of the first release unless the requirements change:",
    nonGoalsDefault: "No exclusions recorded yet.",
    flowSignIn: (who) => `${who} sign in and land on their dashboard.`,
    flowCore: (who, feature) => `${who} use ${feature} to complete their daily work.`,
    flowAdmin: "An administrator manages users and their roles.",
    flowNote: "Flows are outlines from the interview. Detail them before building.",
    nonFunctional: [
      "Pages respond quickly on a mid-range phone over a mobile connection.",
      "The interface meets WCAG 2.2 AA: keyboard access, visible focus and sufficient contrast.",
      "Every change to important data is attributable to a user and a time.",
    ],
    platform: (platforms) => `Supported platforms: ${platforms}.`,
    securityAuth: "Sessions are server-validated; passwords are never stored in plain text.",
    securityRoles: "Every operation checks the user's role on the server.",
    securityData:
      "Input is validated at every system boundary and secrets never reach the browser.",
    securityNoAuth: "No user accounts; public pages expose no private data.",
    landing: (concept) => `Public landing page concept: ${concept}.`,
    acceptance: (feature) =>
      `${feature} works end to end for its intended users, including empty and error states.`,
  },
  plan: {
    title: "Plan",
    intro:
      "Initial plan generated from the requirements. Milestones run in order; tasks inside a milestone can move.",
    milestones: {
      foundation: {
        title: "Foundation",
        goal: "A running application with data, sign-in and navigation in place.",
      },
      core: {
        title: "Core features",
        goal: "The features that make the product useful, in priority order.",
      },
      launch: {
        title: "Quality and launch",
        goal: "Verified, deployed and ready for the first users.",
      },
    },
    tasks: {
      setup: "Set up the application and repository",
      database: "Configure the database and schema",
      auth: "Implement authentication",
      shell: "Create the application shell and navigation",
      roles: "Define roles and permissions",
      feature: (feature) => `Build ${feature}`,
      openQuestions: "Resolve open questions from the interview",
      tests: "Write tests for the critical user flows",
      deploy: (target) => `Set up deployment to ${target}`,
      landing: (concept) => `Build the landing page (${concept})`,
    },
  },
  memory: {
    goal: "Project goal",
    architecture: (value) => `Architecture: ${value}`,
    database: (value) => `Database: ${value}`,
    deployment: (value) => `Deployment: ${value}`,
    auth: (value) => `Authentication: ${value}`,
    build: (value) => `Build strategy: ${value}`,
    landing: (value) => `Landing concept: ${value}`,
    constraints: "Constraints",
    reason: (reason) => `Reason: ${reason}`,
  },
  memoryCategories: {
    architecture: "Architecture",
    product: "Product",
    design: "Design",
    technical: "Technical",
    business: "Business",
    user_preference: "User preference",
    decision: "Decision",
    constraint: "Constraint",
    integration: "Integration",
  },
  decisions: {
    application: "Which application framework should the project use?",
    database: "Which database should the project use?",
    auth: "How do users sign in?",
    build: "How will the project be built?",
    context: "Decided when the project was created from the interview recommendation.",
  },
  agents: {
    saqina: { name: "Saqina Dev", provider: "Saqina" },
    claude: { name: "Claude", provider: "Anthropic" },
    codex: { name: "Codex", provider: "OpenAI" },
    cursor: { name: "Cursor", provider: "Anysphere" },
    kiro: { name: "Kiro", provider: "AWS" },
    hermes: { name: "Hermes", provider: "Nous Research" },
    antigravity: { name: "Antigravity", provider: "Google" },
    openclaw: { name: "OpenClaw", provider: "OpenClaw" },
    custom: { name: "Custom agent", provider: "Custom" },
  },
};
