import { en } from "./en";
import type { GeneratorCopy } from "./types";

export const id: GeneratorCopy = {
  priorities: { critical: "Kritis", high: "Tinggi", medium: "Sedang", low: "Rendah" },
  statuses: {
    confirmed: "Terkonfirmasi",
    inferred: "Disimpulkan",
    unknown: "Belum diketahui",
    conflicting: "Bertentangan",
  },
  inferredMark: "(disimpulkan, konfirmasi)",
  none: "Belum ada.",
  toBeDefined: "Belum ditentukan.",
  prd: {
    title: "Product Requirements Document",
    draftNote:
      "Draf dibuat dari interview proyek. Item bertanda disimpulkan tidak dinyatakan langsung; konfirmasi atau ubah.",
    headings: [
      "Ringkasan",
      "Masalah",
      "Tujuan",
      "Di Luar Cakupan",
      "Target Pengguna",
      "Peran Pengguna",
      "Fitur Inti",
      "Alur Pengguna",
      "Kebutuhan Fungsional",
      "Kebutuhan Non-Fungsional",
      "Integrasi",
      "Kebutuhan Data",
      "Keamanan",
      "Kebutuhan UX",
      "Rekomendasi Teknis",
      "Risiko",
      "Pertanyaan Terbuka",
      "Kriteria Penerimaan",
    ],
    type: "Tipe",
    complexity: "Kompleksitas",
    problem: (objective) => `Produk ini dibuat untuk: ${objective}`,
    noObjective: "Masalah belum dijelaskan. Tambahkan di interview atau ubah bagian ini.",
    goalFeature: (feature) => `Menghadirkan ${feature} di rilis pertama.`,
    nonGoalsIntro: "Tidak termasuk rilis pertama kecuali kebutuhan berubah:",
    nonGoalsDefault: "Belum ada pengecualian yang dicatat.",
    flowSignIn: (who) => `${who} login dan masuk ke dashboard mereka.`,
    flowCore: (who, feature) => `${who} memakai ${feature} untuk pekerjaan sehari-hari.`,
    flowAdmin: "Administrator mengelola pengguna dan perannya.",
    flowNote: "Alur ini garis besar dari interview. Rinci sebelum membangun.",
    nonFunctional: [
      "Halaman merespons cepat di ponsel kelas menengah dengan koneksi seluler.",
      "Antarmuka memenuhi WCAG 2.2 AA: akses keyboard, fokus terlihat dan kontras cukup.",
      "Setiap perubahan data penting tercatat siapa dan kapan.",
    ],
    platform: (platforms) => `Platform yang didukung: ${platforms}.`,
    securityAuth: "Sesi divalidasi di server; kata sandi tidak pernah disimpan dalam teks biasa.",
    securityRoles: "Setiap operasi memeriksa peran pengguna di server.",
    securityData:
      "Input divalidasi di setiap batas sistem dan secret tidak pernah sampai ke browser.",
    securityNoAuth: "Tanpa akun pengguna; halaman publik tidak menampilkan data pribadi.",
    landing: (concept) => `Konsep landing page publik: ${concept}.`,
    acceptance: (feature) =>
      `${feature} berjalan dari awal sampai akhir untuk penggunanya, termasuk kondisi kosong dan error.`,
  },
  plan: {
    title: "Plan",
    intro:
      "Rencana awal dibuat dari requirement. Milestone berjalan berurutan; task di dalam milestone bisa dipindah.",
    milestones: {
      foundation: {
        title: "Fondasi",
        goal: "Aplikasi berjalan dengan data, login dan navigasi siap.",
      },
      core: { title: "Fitur inti", goal: "Fitur yang membuat produk berguna, urut prioritas." },
      launch: {
        title: "Kualitas dan rilis",
        goal: "Teruji, ter-deploy dan siap untuk pengguna pertama.",
      },
    },
    tasks: {
      setup: "Siapkan aplikasi dan repository",
      database: "Konfigurasi database dan skema",
      auth: "Implementasi autentikasi",
      shell: "Buat application shell dan navigasi",
      roles: "Tentukan peran dan hak akses",
      feature: (feature) => `Bangun ${feature}`,
      openQuestions: "Selesaikan pertanyaan terbuka dari interview",
      tests: "Tulis test untuk alur pengguna yang kritis",
      deploy: (target) => `Siapkan deployment ke ${target}`,
      landing: (concept) => `Bangun landing page (${concept})`,
    },
  },
  memory: {
    goal: "Tujuan proyek",
    architecture: (value) => `Arsitektur: ${value}`,
    database: (value) => `Database: ${value}`,
    deployment: (value) => `Deployment: ${value}`,
    auth: (value) => `Autentikasi: ${value}`,
    build: (value) => `Strategi build: ${value}`,
    landing: (value) => `Konsep landing: ${value}`,
    constraints: "Batasan",
    reason: (reason) => `Alasan: ${reason}`,
  },
  memoryCategories: {
    architecture: "Arsitektur",
    product: "Produk",
    design: "Desain",
    technical: "Teknis",
    business: "Bisnis",
    user_preference: "Preferensi pengguna",
    decision: "Keputusan",
    constraint: "Batasan",
    integration: "Integrasi",
  },
  decisions: {
    application: "Framework aplikasi apa yang dipakai proyek ini?",
    database: "Database apa yang dipakai proyek ini?",
    auth: "Bagaimana pengguna login?",
    build: "Bagaimana proyek ini dibangun?",
    context: "Diputuskan saat proyek dibuat dari rekomendasi interview.",
  },
  // Product names are not translated.
  agents: en.agents,
};
